project:
  type: book
  output-dir: ../_docs

book:
  title: "Fundamentals of GitHub Action Workflows"
  chapters:
    - index.qmd
    - 02-repo.qmd
    - 03-gha.qmd
    - 04-containers.qmd

format:
  html:
    toc: true
